2019-10-08 16:50:58,450 [Dummy-1: 123145397166080]/Users/chengyinliu/anaconda3/lib/python3.7/site-packages/django/db/backends/utils.py:execute:111 DEBUG - (0.002) SELECT @@SQL_AUTO_IS_NULL; args=None
2019-10-08 16:50:58,450 [Dummy-1: 123145397166080]/Users/chengyinliu/anaconda3/lib/python3.7/site-packages/django/db/backends/utils.py:execute:111 DEBUG - (0.000) SET SESSION TRANSACTION ISOLATION LEVEL READ COMMITTED; args=None
2019-10-08 16:50:58,452 [Dummy-1: 123145397166080]/Users/chengyinliu/anaconda3/lib/python3.7/site-packages/django/db/backends/utils.py:execute:111 DEBUG - (0.001) SELECT VERSION(); args=None
2019-10-08 16:50:58,484 [Dummy-1: 123145397166080]/Users/chengyinliu/anaconda3/lib/python3.7/site-packages/django/db/backends/utils.py:execute:111 DEBUG - (0.000) SET SESSION TRANSACTION ISOLATION LEVEL READ COMMITTED; args=None
2019-10-08 16:50:58,498 [Dummy-1: 123145397166080]/Users/chengyinliu/anaconda3/lib/python3.7/site-packages/django/db/backends/utils.py:execute:111 DEBUG - (0.014) SHOW FULL TABLES; args=None
2019-10-08 16:50:58,511 [Dummy-1: 123145397166080]/Users/chengyinliu/anaconda3/lib/python3.7/site-packages/django/db/backends/utils.py:execute:111 DEBUG - (0.011) SELECT `django_migrations`.`app`, `django_migrations`.`name` FROM `django_migrations`; args=()
2019-10-08 16:50:58,517 [Dummy-1: 123145397166080]/Users/chengyinliu/WeChatProjects/backend/module/middleware.py:__init__:14 INFO - Build StatisticsMiddleware.
2019-10-08 16:52:20,645 [Thread-2: 123145402421248]/Users/chengyinliu/anaconda3/lib/python3.7/site-packages/django/template/base.py:_resolve_lookup:878 DEBUG - Exception while resolving variable 'name' in template 'unknown'.
Traceback (most recent call last):
  File "/Users/chengyinliu/anaconda3/lib/python3.7/site-packages/django/core/handlers/exception.py", line 35, in inner
    response = get_response(request)
  File "/Users/chengyinliu/anaconda3/lib/python3.7/site-packages/django/core/handlers/base.py", line 113, in _get_response
    resolver_match = resolver.resolve(request.path_info)
  File "/Users/chengyinliu/anaconda3/lib/python3.7/site-packages/django/urls/resolvers.py", line 527, in resolve
    raise Resolver404({'tried': tried, 'path': new_path})
django.urls.exceptions.Resolver404: {'tried': [[<URLResolver <URLPattern list> (admin:admin) 'admin/'>], [<URLResolver <module 'backend.version_1_0' from '/Users/chengyinliu/WeChatProjects/backend/backend/version_1_0.py'> (None:None) 'api/v1.0/'>]], 'path': 'all/rss/'}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/chengyinliu/anaconda3/lib/python3.7/site-packages/django/template/base.py", line 835, in _resolve_lookup
    current = current[bit]
TypeError: 'URLResolver' object is not subscriptable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/chengyinliu/anaconda3/lib/python3.7/site-packages/django/template/base.py", line 843, in _resolve_lookup
    current = getattr(current, bit)
AttributeError: 'URLResolver' object has no attribute 'name'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/chengyinliu/anaconda3/lib/python3.7/site-packages/django/template/base.py", line 849, in _resolve_lookup
    current = current[int(bit)]
ValueError: invalid literal for int() with base 10: 'name'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/chengyinliu/anaconda3/lib/python3.7/site-packages/django/template/base.py", line 856, in _resolve_lookup
    (bit, current))  # missing attribute
django.template.base.VariableDoesNotExist: Failed lookup for key [name] in <URLResolver <URLPattern list> (admin:admin) 'admin/'>
2019-10-08 16:52:20,650 [Thread-2: 123145402421248]/Users/chengyinliu/anaconda3/lib/python3.7/site-packages/django/template/base.py:_resolve_lookup:878 DEBUG - Exception while resolving variable 'name' in template 'unknown'.
Traceback (most recent call last):
  File "/Users/chengyinliu/anaconda3/lib/python3.7/site-packages/django/core/handlers/exception.py", line 35, in inner
    response = get_response(request)
  File "/Users/chengyinliu/anaconda3/lib/python3.7/site-packages/django/core/handlers/base.py", line 113, in _get_response
    resolver_match = resolver.resolve(request.path_info)
  File "/Users/chengyinliu/anaconda3/lib/python3.7/site-packages/django/urls/resolvers.py", line 527, in resolve
    raise Resolver404({'tried': tried, 'path': new_path})
django.urls.exceptions.Resolver404: {'tried': [[<URLResolver <URLPattern list> (admin:admin) 'admin/'>], [<URLResolver <module 'backend.version_1_0' from '/Users/chengyinliu/WeChatProjects/backend/backend/version_1_0.py'> (None:None) 'api/v1.0/'>]], 'path': 'all/rss/'}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/chengyinliu/anaconda3/lib/python3.7/site-packages/django/template/base.py", line 835, in _resolve_lookup
    current = current[bit]
TypeError: 'URLResolver' object is not subscriptable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/chengyinliu/anaconda3/lib/python3.7/site-packages/django/template/base.py", line 843, in _resolve_lookup
    current = getattr(current, bit)
AttributeError: 'URLResolver' object has no attribute 'name'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/chengyinliu/anaconda3/lib/python3.7/site-packages/django/template/base.py", line 849, in _resolve_lookup
    current = current[int(bit)]
ValueError: invalid literal for int() with base 10: 'name'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/chengyinliu/anaconda3/lib/python3.7/site-packages/django/template/base.py", line 856, in _resolve_lookup
    (bit, current))  # missing attribute
django.template.base.VariableDoesNotExist: Failed lookup for key [name] in <URLResolver <module 'backend.version_1_0' from '/Users/chengyinliu/WeChatProjects/backend/backend/version_1_0.py'> (None:None) 'api/v1.0/'>
2019-10-08 16:52:20,651 [Thread-2: 123145402421248]/Users/chengyinliu/anaconda3/lib/python3.7/site-packages/django/core/handlers/base.py:get_response:93 WARNING - Not Found: /all/rss/
2019-10-08 16:52:20,652 [Thread-2: 123145402421248]/Users/chengyinliu/anaconda3/lib/python3.7/site-packages/django/core/servers/basehttp.py:log_message:124 WARNING - "GET /all/rss/ HTTP/1.1" 404 2073
2019-10-08 16:55:18,289 [Thread-3: 123145402421248]/Users/chengyinliu/anaconda3/lib/python3.7/site-packages/django/core/servers/basehttp.py:log_message:124 INFO - "GET /api/v1.0/service/test HTTP/1.1" 200 11
2019-10-08 16:55:18,292 [Thread-4: 123145402421248]/Users/chengyinliu/anaconda3/lib/python3.7/site-packages/django/core/servers/basehttp.py:log_message:124 INFO - "GET /api/v1.0/service/image/list HTTP/1.1" 200 143
2019-10-08 16:55:19,299 [Thread-5: 123145402421248]/Users/chengyinliu/anaconda3/lib/python3.7/site-packages/django/core/servers/basehttp.py:log_message:124 INFO - "GET /api/v1.0/service/test HTTP/1.1" 200 11
2019-10-08 16:55:19,304 [Thread-6: 123145402421248]/Users/chengyinliu/anaconda3/lib/python3.7/site-packages/django/core/servers/basehttp.py:log_message:124 INFO - "GET /api/v1.0/service/image/list HTTP/1.1" 200 143
2019-10-08 16:55:20,317 [Thread-7: 123145402421248]/Users/chengyinliu/anaconda3/lib/python3.7/site-packages/django/core/servers/basehttp.py:log_message:124 INFO - "GET /api/v1.0/service/test HTTP/1.1" 200 11
2019-10-08 16:55:20,322 [Thread-8: 123145402421248]/Users/chengyinliu/anaconda3/lib/python3.7/site-packages/django/core/servers/basehttp.py:log_message:124 INFO - "GET /api/v1.0/service/image/list HTTP/1.1" 200 143
2019-10-08 16:55:21,331 [Thread-9: 123145402421248]/Users/chengyinliu/anaconda3/lib/python3.7/site-packages/django/core/servers/basehttp.py:log_message:124 INFO - "GET /api/v1.0/service/test HTTP/1.1" 200 11
2019-10-08 16:55:21,336 [Thread-10: 123145402421248]/Users/chengyinliu/anaconda3/lib/python3.7/site-packages/django/core/servers/basehttp.py:log_message:124 INFO - "GET /api/v1.0/service/image/list HTTP/1.1" 200 143
2019-10-08 16:55:22,348 [Thread-11: 123145402421248]/Users/chengyinliu/anaconda3/lib/python3.7/site-packages/django/core/servers/basehttp.py:log_message:124 INFO - "GET /api/v1.0/service/test HTTP/1.1" 200 11
2019-10-08 16:55:22,354 [Thread-12: 123145402421248]/Users/chengyinliu/anaconda3/lib/python3.7/site-packages/django/core/servers/basehttp.py:log_message:124 INFO - "GET /api/v1.0/service/image/list HTTP/1.1" 200 143
2019-10-08 16:55:23,362 [Thread-13: 123145402421248]/Users/chengyinliu/anaconda3/lib/python3.7/site-packages/django/core/servers/basehttp.py:log_message:124 INFO - "GET /api/v1.0/service/test HTTP/1.1" 200 11
2019-10-08 16:55:23,369 [Thread-14: 123145402421248]/Users/chengyinliu/anaconda3/lib/python3.7/site-packages/django/core/servers/basehttp.py:log_message:124 INFO - "GET /api/v1.0/service/image/list HTTP/1.1" 200 143
2019-10-08 16:55:24,376 [Thread-15: 123145402421248]/Users/chengyinliu/anaconda3/lib/python3.7/site-packages/django/core/servers/basehttp.py:log_message:124 INFO - "GET /api/v1.0/service/test HTTP/1.1" 200 11
2019-10-08 16:55:24,379 [Thread-16: 123145402421248]/Users/chengyinliu/anaconda3/lib/python3.7/site-packages/django/core/servers/basehttp.py:log_message:124 INFO - "GET /api/v1.0/service/image/list HTTP/1.1" 200 143
2019-10-08 16:55:25,387 [Thread-17: 123145402421248]/Users/chengyinliu/anaconda3/lib/python3.7/site-packages/django/core/servers/basehttp.py:log_message:124 INFO - "GET /api/v1.0/service/test HTTP/1.1" 200 11
2019-10-08 16:55:25,392 [Thread-18: 123145402421248]/Users/chengyinliu/anaconda3/lib/python3.7/site-packages/django/core/servers/basehttp.py:log_message:124 INFO - "GET /api/v1.0/service/image/list HTTP/1.1" 200 143
2019-10-08 16:55:26,396 [Thread-19: 123145402421248]/Users/chengyinliu/anaconda3/lib/python3.7/site-packages/django/core/servers/basehttp.py:log_message:124 INFO - "GET /api/v1.0/service/test HTTP/1.1" 200 11
2019-10-08 16:55:26,400 [Thread-20: 123145402421248]/Users/chengyinliu/anaconda3/lib/python3.7/site-packages/django/core/servers/basehttp.py:log_message:124 INFO - "GET /api/v1.0/service/image/list HTTP/1.1" 200 143
2019-10-08 16:55:27,412 [Thread-21: 123145402421248]/Users/chengyinliu/anaconda3/lib/python3.7/site-packages/django/core/servers/basehttp.py:log_message:124 INFO - "GET /api/v1.0/service/test HTTP/1.1" 200 11
2019-10-08 16:55:27,420 [Thread-22: 123145402421248]/Users/chengyinliu/anaconda3/lib/python3.7/site-packages/django/core/servers/basehttp.py:log_message:124 INFO - "GET /api/v1.0/service/image/list HTTP/1.1" 200 143
2019-10-08 16:55:28,427 [Thread-23: 123145402421248]/Users/chengyinliu/anaconda3/lib/python3.7/site-packages/django/core/servers/basehttp.py:log_message:124 INFO - "GET /api/v1.0/service/test HTTP/1.1" 200 11
2019-10-08 16:55:28,434 [Thread-24: 123145402421248]/Users/chengyinliu/anaconda3/lib/python3.7/site-packages/django/core/servers/basehttp.py:log_message:124 INFO - "GET /api/v1.0/service/image/list HTTP/1.1" 200 143
2019-10-08 16:55:29,444 [Thread-25: 123145402421248]/Users/chengyinliu/anaconda3/lib/python3.7/site-packages/django/core/servers/basehttp.py:log_message:124 INFO - "GET /api/v1.0/service/test HTTP/1.1" 200 11
2019-10-08 16:55:29,449 [Thread-26: 123145402421248]/Users/chengyinliu/anaconda3/lib/python3.7/site-packages/django/core/servers/basehttp.py:log_message:124 INFO - "GET /api/v1.0/service/image/list HTTP/1.1" 200 143
2019-10-08 16:55:30,461 [Thread-27: 123145402421248]/Users/chengyinliu/anaconda3/lib/python3.7/site-packages/django/core/servers/basehttp.py:log_message:124 INFO - "GET /api/v1.0/service/test HTTP/1.1" 200 11
2019-10-08 16:55:30,467 [Thread-28: 123145402421248]/Users/chengyinliu/anaconda3/lib/python3.7/site-packages/django/core/servers/basehttp.py:log_message:124 INFO - "GET /api/v1.0/service/image/list HTTP/1.1" 200 143
2019-10-08 16:55:31,478 [Thread-29: 123145402421248]/Users/chengyinliu/anaconda3/lib/python3.7/site-packages/django/core/servers/basehttp.py:log_message:124 INFO - "GET /api/v1.0/service/test HTTP/1.1" 200 11
2019-10-08 16:55:31,485 [Thread-30: 123145402421248]/Users/chengyinliu/anaconda3/lib/python3.7/site-packages/django/core/servers/basehttp.py:log_message:124 INFO - "GET /api/v1.0/service/image/list HTTP/1.1" 200 143
2019-10-08 16:55:32,497 [Thread-31: 123145402421248]/Users/chengyinliu/anaconda3/lib/python3.7/site-packages/django/core/servers/basehttp.py:log_message:124 INFO - "GET /api/v1.0/service/test HTTP/1.1" 200 11
2019-10-08 16:55:32,502 [Thread-32: 123145402421248]/Users/chengyinliu/anaconda3/lib/python3.7/site-packages/django/core/servers/basehttp.py:log_message:124 INFO - "GET /api/v1.0/service/image/list HTTP/1.1" 200 143
2019-10-08 16:55:33,510 [Thread-33: 123145402421248]/Users/chengyinliu/anaconda3/lib/python3.7/site-packages/django/core/servers/basehttp.py:log_message:124 INFO - "GET /api/v1.0/service/test HTTP/1.1" 200 11
2019-10-08 16:55:33,515 [Thread-34: 123145402421248]/Users/chengyinliu/anaconda3/lib/python3.7/site-packages/django/core/servers/basehttp.py:log_message:124 INFO - "GET /api/v1.0/service/image/list HTTP/1.1" 200 143
2019-10-08 16:55:34,524 [Thread-35: 123145402421248]/Users/chengyinliu/anaconda3/lib/python3.7/site-packages/django/core/servers/basehttp.py:log_message:124 INFO - "GET /api/v1.0/service/test HTTP/1.1" 200 11
2019-10-08 16:55:34,530 [Thread-36: 123145402421248]/Users/chengyinliu/anaconda3/lib/python3.7/site-packages/django/core/servers/basehttp.py:log_message:124 INFO - "GET /api/v1.0/service/image/list HTTP/1.1" 200 143
2019-10-08 16:55:35,543 [Thread-37: 123145402421248]/Users/chengyinliu/anaconda3/lib/python3.7/site-packages/django/core/servers/basehttp.py:log_message:124 INFO - "GET /api/v1.0/service/test HTTP/1.1" 200 11
2019-10-08 16:55:35,548 [Thread-38: 123145402421248]/Users/chengyinliu/anaconda3/lib/python3.7/site-packages/django/core/servers/basehttp.py:log_message:124 INFO - "GET /api/v1.0/service/image/list HTTP/1.1" 200 143
2019-10-08 16:55:36,558 [Thread-39: 123145402421248]/Users/chengyinliu/anaconda3/lib/python3.7/site-packages/django/core/servers/basehttp.py:log_message:124 INFO - "GET /api/v1.0/service/test HTTP/1.1" 200 11
2019-10-08 16:55:36,563 [Thread-40: 123145402421248]/Users/chengyinliu/anaconda3/lib/python3.7/site-packages/django/core/servers/basehttp.py:log_message:124 INFO - "GET /api/v1.0/service/image/list HTTP/1.1" 200 143
2019-10-08 16:55:37,572 [Thread-41: 123145402421248]/Users/chengyinliu/anaconda3/lib/python3.7/site-packages/django/core/servers/basehttp.py:log_message:124 INFO - "GET /api/v1.0/service/test HTTP/1.1" 200 11
2019-10-08 16:55:37,578 [Thread-42: 123145402421248]/Users/chengyinliu/anaconda3/lib/python3.7/site-packages/django/core/servers/basehttp.py:log_message:124 INFO - "GET /api/v1.0/service/image/list HTTP/1.1" 200 143
2019-10-08 16:55:38,585 [Thread-43: 123145402421248]/Users/chengyinliu/anaconda3/lib/python3.7/site-packages/django/core/servers/basehttp.py:log_message:124 INFO - "GET /api/v1.0/service/test HTTP/1.1" 200 11
2019-10-08 16:55:38,590 [Thread-44: 123145402421248]/Users/chengyinliu/anaconda3/lib/python3.7/site-packages/django/core/servers/basehttp.py:log_message:124 INFO - "GET /api/v1.0/service/image/list HTTP/1.1" 200 143
2019-10-08 16:55:39,596 [Thread-45: 123145402421248]/Users/chengyinliu/anaconda3/lib/python3.7/site-packages/django/core/servers/basehttp.py:log_message:124 INFO - "GET /api/v1.0/service/test HTTP/1.1" 200 11
2019-10-08 16:55:39,601 [Thread-46: 123145402421248]/Users/chengyinliu/anaconda3/lib/python3.7/site-packages/django/core/servers/basehttp.py:log_message:124 INFO - "GET /api/v1.0/service/image/list HTTP/1.1" 200 143
2019-10-08 16:55:40,610 [Thread-47: 123145402421248]/Users/chengyinliu/anaconda3/lib/python3.7/site-packages/django/core/servers/basehttp.py:log_message:124 INFO - "GET /api/v1.0/service/test HTTP/1.1" 200 11
2019-10-08 16:55:40,617 [Thread-48: 123145402421248]/Users/chengyinliu/anaconda3/lib/python3.7/site-packages/django/core/servers/basehttp.py:log_message:124 INFO - "GET /api/v1.0/service/image/list HTTP/1.1" 200 143
2019-10-08 16:55:41,624 [Thread-49: 123145402421248]/Users/chengyinliu/anaconda3/lib/python3.7/site-packages/django/core/servers/basehttp.py:log_message:124 INFO - "GET /api/v1.0/service/test HTTP/1.1" 200 11
2019-10-08 16:55:41,629 [Thread-50: 123145402421248]/Users/chengyinliu/anaconda3/lib/python3.7/site-packages/django/core/servers/basehttp.py:log_message:124 INFO - "GET /api/v1.0/service/image/list HTTP/1.1" 200 143
2019-10-08 16:55:42,638 [Thread-51: 123145402421248]/Users/chengyinliu/anaconda3/lib/python3.7/site-packages/django/core/servers/basehttp.py:log_message:124 INFO - "GET /api/v1.0/service/test HTTP/1.1" 200 11
2019-10-08 16:55:42,645 [Thread-52: 123145402421248]/Users/chengyinliu/anaconda3/lib/python3.7/site-packages/django/core/servers/basehttp.py:log_message:124 INFO - "GET /api/v1.0/service/image/list HTTP/1.1" 200 143
2019-10-08 16:57:11,672 [Dummy-1: 123145320398848]/Users/chengyinliu/anaconda3/lib/python3.7/site-packages/django/db/backends/utils.py:execute:111 DEBUG - (0.000) SELECT @@SQL_AUTO_IS_NULL; args=None
2019-10-08 16:57:11,672 [Dummy-1: 123145320398848]/Users/chengyinliu/anaconda3/lib/python3.7/site-packages/django/db/backends/utils.py:execute:111 DEBUG - (0.000) SET SESSION TRANSACTION ISOLATION LEVEL READ COMMITTED; args=None
2019-10-08 16:57:11,673 [Dummy-1: 123145320398848]/Users/chengyinliu/anaconda3/lib/python3.7/site-packages/django/db/backends/utils.py:execute:111 DEBUG - (0.000) SELECT VERSION(); args=None
2019-10-08 16:57:11,690 [Dummy-1: 123145320398848]/Users/chengyinliu/anaconda3/lib/python3.7/site-packages/django/db/backends/utils.py:execute:111 DEBUG - (0.000) SET SESSION TRANSACTION ISOLATION LEVEL READ COMMITTED; args=None
2019-10-08 16:57:11,693 [Dummy-1: 123145320398848]/Users/chengyinliu/anaconda3/lib/python3.7/site-packages/django/db/backends/utils.py:execute:111 DEBUG - (0.003) SHOW FULL TABLES; args=None
2019-10-08 16:57:11,696 [Dummy-1: 123145320398848]/Users/chengyinliu/anaconda3/lib/python3.7/site-packages/django/db/backends/utils.py:execute:111 DEBUG - (0.001) SELECT `django_migrations`.`app`, `django_migrations`.`name` FROM `django_migrations`; args=()
2019-10-08 16:57:11,699 [Dummy-1: 123145320398848]/Users/chengyinliu/WeChatProjects/backend/module/middleware.py:__init__:14 INFO - Build StatisticsMiddleware.
2019-10-08 16:58:06,594 [Dummy-1: 123145455476736]/Users/chengyinliu/anaconda3/lib/python3.7/site-packages/django/db/backends/utils.py:execute:111 DEBUG - (0.000) SELECT @@SQL_AUTO_IS_NULL; args=None
2019-10-08 16:58:06,594 [Dummy-1: 123145455476736]/Users/chengyinliu/anaconda3/lib/python3.7/site-packages/django/db/backends/utils.py:execute:111 DEBUG - (0.000) SET SESSION TRANSACTION ISOLATION LEVEL READ COMMITTED; args=None
2019-10-08 16:58:06,594 [Dummy-1: 123145455476736]/Users/chengyinliu/anaconda3/lib/python3.7/site-packages/django/db/backends/utils.py:execute:111 DEBUG - (0.000) SELECT VERSION(); args=None
2019-10-08 16:58:06,611 [Dummy-1: 123145455476736]/Users/chengyinliu/anaconda3/lib/python3.7/site-packages/django/db/backends/utils.py:execute:111 DEBUG - (0.000) SET SESSION TRANSACTION ISOLATION LEVEL READ COMMITTED; args=None
2019-10-08 16:58:06,612 [Dummy-1: 123145455476736]/Users/chengyinliu/anaconda3/lib/python3.7/site-packages/django/db/backends/utils.py:execute:111 DEBUG - (0.001) SHOW FULL TABLES; args=None
2019-10-08 16:58:06,614 [Dummy-1: 123145455476736]/Users/chengyinliu/anaconda3/lib/python3.7/site-packages/django/db/backends/utils.py:execute:111 DEBUG - (0.001) SELECT `django_migrations`.`app`, `django_migrations`.`name` FROM `django_migrations`; args=()
2019-10-08 16:58:06,617 [Dummy-1: 123145455476736]/Users/chengyinliu/WeChatProjects/backend/module/middleware.py:__init__:14 INFO - Build StatisticsMiddleware.
2019-10-08 16:58:21,488 [Dummy-1: 123145412255744]/Users/chengyinliu/anaconda3/lib/python3.7/site-packages/django/db/backends/utils.py:execute:111 DEBUG - (0.000) SELECT @@SQL_AUTO_IS_NULL; args=None
2019-10-08 16:58:21,489 [Dummy-1: 123145412255744]/Users/chengyinliu/anaconda3/lib/python3.7/site-packages/django/db/backends/utils.py:execute:111 DEBUG - (0.000) SET SESSION TRANSACTION ISOLATION LEVEL READ COMMITTED; args=None
2019-10-08 16:58:21,489 [Dummy-1: 123145412255744]/Users/chengyinliu/anaconda3/lib/python3.7/site-packages/django/db/backends/utils.py:execute:111 DEBUG - (0.000) SELECT VERSION(); args=None
2019-10-08 16:58:21,505 [Dummy-1: 123145412255744]/Users/chengyinliu/anaconda3/lib/python3.7/site-packages/django/db/backends/utils.py:execute:111 DEBUG - (0.000) SET SESSION TRANSACTION ISOLATION LEVEL READ COMMITTED; args=None
2019-10-08 16:58:21,506 [Dummy-1: 123145412255744]/Users/chengyinliu/anaconda3/lib/python3.7/site-packages/django/db/backends/utils.py:execute:111 DEBUG - (0.001) SHOW FULL TABLES; args=None
2019-10-08 16:58:21,508 [Dummy-1: 123145412255744]/Users/chengyinliu/anaconda3/lib/python3.7/site-packages/django/db/backends/utils.py:execute:111 DEBUG - (0.001) SELECT `django_migrations`.`app`, `django_migrations`.`name` FROM `django_migrations`; args=()
2019-10-08 16:58:21,512 [Dummy-1: 123145412255744]/Users/chengyinliu/WeChatProjects/backend/module/middleware.py:__init__:14 INFO - Build StatisticsMiddleware.
2019-10-08 16:59:58,576 [Dummy-1: 123145333043200]/Users/chengyinliu/anaconda3/lib/python3.7/site-packages/django/db/backends/utils.py:execute:111 DEBUG - (0.000) SELECT @@SQL_AUTO_IS_NULL; args=None
2019-10-08 16:59:58,576 [Dummy-1: 123145333043200]/Users/chengyinliu/anaconda3/lib/python3.7/site-packages/django/db/backends/utils.py:execute:111 DEBUG - (0.000) SET SESSION TRANSACTION ISOLATION LEVEL READ COMMITTED; args=None
2019-10-08 16:59:58,577 [Dummy-1: 123145333043200]/Users/chengyinliu/anaconda3/lib/python3.7/site-packages/django/db/backends/utils.py:execute:111 DEBUG - (0.000) SELECT VERSION(); args=None
2019-10-08 16:59:58,595 [Dummy-1: 123145333043200]/Users/chengyinliu/anaconda3/lib/python3.7/site-packages/django/db/backends/utils.py:execute:111 DEBUG - (0.000) SET SESSION TRANSACTION ISOLATION LEVEL READ COMMITTED; args=None
2019-10-08 16:59:58,596 [Dummy-1: 123145333043200]/Users/chengyinliu/anaconda3/lib/python3.7/site-packages/django/db/backends/utils.py:execute:111 DEBUG - (0.001) SHOW FULL TABLES; args=None
2019-10-08 16:59:58,598 [Dummy-1: 123145333043200]/Users/chengyinliu/anaconda3/lib/python3.7/site-packages/django/db/backends/utils.py:execute:111 DEBUG - (0.001) SELECT `django_migrations`.`app`, `django_migrations`.`name` FROM `django_migrations`; args=()
2019-10-08 16:59:58,602 [Dummy-1: 123145333043200]/Users/chengyinliu/WeChatProjects/backend/module/middleware.py:__init__:14 INFO - Build StatisticsMiddleware.
2019-10-08 17:00:20,635 [Dummy-1: 123145348808704]/Users/chengyinliu/anaconda3/lib/python3.7/site-packages/django/db/backends/utils.py:execute:111 DEBUG - (0.000) SELECT @@SQL_AUTO_IS_NULL; args=None
2019-10-08 17:00:20,635 [Dummy-1: 123145348808704]/Users/chengyinliu/anaconda3/lib/python3.7/site-packages/django/db/backends/utils.py:execute:111 DEBUG - (0.000) SET SESSION TRANSACTION ISOLATION LEVEL READ COMMITTED; args=None
2019-10-08 17:00:20,635 [Dummy-1: 123145348808704]/Users/chengyinliu/anaconda3/lib/python3.7/site-packages/django/db/backends/utils.py:execute:111 DEBUG - (0.000) SELECT VERSION(); args=None
2019-10-08 17:00:20,653 [Dummy-1: 123145348808704]/Users/chengyinliu/anaconda3/lib/python3.7/site-packages/django/db/backends/utils.py:execute:111 DEBUG - (0.000) SET SESSION TRANSACTION ISOLATION LEVEL READ COMMITTED; args=None
2019-10-08 17:00:20,654 [Dummy-1: 123145348808704]/Users/chengyinliu/anaconda3/lib/python3.7/site-packages/django/db/backends/utils.py:execute:111 DEBUG - (0.001) SHOW FULL TABLES; args=None
2019-10-08 17:00:20,656 [Dummy-1: 123145348808704]/Users/chengyinliu/anaconda3/lib/python3.7/site-packages/django/db/backends/utils.py:execute:111 DEBUG - (0.001) SELECT `django_migrations`.`app`, `django_migrations`.`name` FROM `django_migrations`; args=()
2019-10-08 17:00:20,660 [Dummy-1: 123145348808704]/Users/chengyinliu/WeChatProjects/backend/module/middleware.py:__init__:14 INFO - Build StatisticsMiddleware.
2019-10-08 17:00:26,272 [Dummy-1: 123145525157888]/Users/chengyinliu/anaconda3/lib/python3.7/site-packages/django/db/backends/utils.py:execute:111 DEBUG - (0.000) SELECT @@SQL_AUTO_IS_NULL; args=None
2019-10-08 17:00:26,273 [Dummy-1: 123145525157888]/Users/chengyinliu/anaconda3/lib/python3.7/site-packages/django/db/backends/utils.py:execute:111 DEBUG - (0.000) SET SESSION TRANSACTION ISOLATION LEVEL READ COMMITTED; args=None
2019-10-08 17:00:26,273 [Dummy-1: 123145525157888]/Users/chengyinliu/anaconda3/lib/python3.7/site-packages/django/db/backends/utils.py:execute:111 DEBUG - (0.000) SELECT VERSION(); args=None
2019-10-08 17:00:26,290 [Dummy-1: 123145525157888]/Users/chengyinliu/anaconda3/lib/python3.7/site-packages/django/db/backends/utils.py:execute:111 DEBUG - (0.000) SET SESSION TRANSACTION ISOLATION LEVEL READ COMMITTED; args=None
2019-10-08 17:00:26,291 [Dummy-1: 123145525157888]/Users/chengyinliu/anaconda3/lib/python3.7/site-packages/django/db/backends/utils.py:execute:111 DEBUG - (0.001) SHOW FULL TABLES; args=None
2019-10-08 17:00:26,293 [Dummy-1: 123145525157888]/Users/chengyinliu/anaconda3/lib/python3.7/site-packages/django/db/backends/utils.py:execute:111 DEBUG - (0.001) SELECT `django_migrations`.`app`, `django_migrations`.`name` FROM `django_migrations`; args=()
2019-10-08 17:00:26,297 [Dummy-1: 123145525157888]/Users/chengyinliu/WeChatProjects/backend/module/middleware.py:__init__:14 INFO - Build StatisticsMiddleware.
2019-10-08 17:00:43,183 [Dummy-1: 123145407012864]/Users/chengyinliu/anaconda3/lib/python3.7/site-packages/django/db/backends/utils.py:execute:111 DEBUG - (0.000) SELECT @@SQL_AUTO_IS_NULL; args=None
2019-10-08 17:00:43,183 [Dummy-1: 123145407012864]/Users/chengyinliu/anaconda3/lib/python3.7/site-packages/django/db/backends/utils.py:execute:111 DEBUG - (0.000) SET SESSION TRANSACTION ISOLATION LEVEL READ COMMITTED; args=None
2019-10-08 17:00:43,183 [Dummy-1: 123145407012864]/Users/chengyinliu/anaconda3/lib/python3.7/site-packages/django/db/backends/utils.py:execute:111 DEBUG - (0.000) SELECT VERSION(); args=None
2019-10-08 17:00:43,200 [Dummy-1: 123145407012864]/Users/chengyinliu/anaconda3/lib/python3.7/site-packages/django/db/backends/utils.py:execute:111 DEBUG - (0.000) SET SESSION TRANSACTION ISOLATION LEVEL READ COMMITTED; args=None
2019-10-08 17:00:43,201 [Dummy-1: 123145407012864]/Users/chengyinliu/anaconda3/lib/python3.7/site-packages/django/db/backends/utils.py:execute:111 DEBUG - (0.001) SHOW FULL TABLES; args=None
2019-10-08 17:00:43,203 [Dummy-1: 123145407012864]/Users/chengyinliu/anaconda3/lib/python3.7/site-packages/django/db/backends/utils.py:execute:111 DEBUG - (0.001) SELECT `django_migrations`.`app`, `django_migrations`.`name` FROM `django_migrations`; args=()
2019-10-08 17:00:43,207 [Dummy-1: 123145407012864]/Users/chengyinliu/WeChatProjects/backend/module/middleware.py:__init__:14 INFO - Build StatisticsMiddleware.
2019-10-08 17:02:20,675 [Thread-2: 123145412268032]/Users/chengyinliu/anaconda3/lib/python3.7/site-packages/django/template/base.py:_resolve_lookup:878 DEBUG - Exception while resolving variable 'name' in template 'unknown'.
Traceback (most recent call last):
  File "/Users/chengyinliu/anaconda3/lib/python3.7/site-packages/django/core/handlers/exception.py", line 35, in inner
    response = get_response(request)
  File "/Users/chengyinliu/anaconda3/lib/python3.7/site-packages/django/core/handlers/base.py", line 113, in _get_response
    resolver_match = resolver.resolve(request.path_info)
  File "/Users/chengyinliu/anaconda3/lib/python3.7/site-packages/django/urls/resolvers.py", line 527, in resolve
    raise Resolver404({'tried': tried, 'path': new_path})
django.urls.exceptions.Resolver404: {'tried': [[<URLResolver <URLPattern list> (admin:admin) 'admin/'>], [<URLResolver <module 'backend.version_1_0' from '/Users/chengyinliu/WeChatProjects/backend/backend/version_1_0.py'> (None:None) 'api/v1.0/'>]], 'path': 'all/rss/'}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/chengyinliu/anaconda3/lib/python3.7/site-packages/django/template/base.py", line 835, in _resolve_lookup
    current = current[bit]
TypeError: 'URLResolver' object is not subscriptable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/chengyinliu/anaconda3/lib/python3.7/site-packages/django/template/base.py", line 843, in _resolve_lookup
    current = getattr(current, bit)
AttributeError: 'URLResolver' object has no attribute 'name'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/chengyinliu/anaconda3/lib/python3.7/site-packages/django/template/base.py", line 849, in _resolve_lookup
    current = current[int(bit)]
ValueError: invalid literal for int() with base 10: 'name'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/chengyinliu/anaconda3/lib/python3.7/site-packages/django/template/base.py", line 856, in _resolve_lookup
    (bit, current))  # missing attribute
django.template.base.VariableDoesNotExist: Failed lookup for key [name] in <URLResolver <URLPattern list> (admin:admin) 'admin/'>
2019-10-08 17:02:20,676 [Thread-2: 123145412268032]/Users/chengyinliu/anaconda3/lib/python3.7/site-packages/django/template/base.py:_resolve_lookup:878 DEBUG - Exception while resolving variable 'name' in template 'unknown'.
Traceback (most recent call last):
  File "/Users/chengyinliu/anaconda3/lib/python3.7/site-packages/django/core/handlers/exception.py", line 35, in inner
    response = get_response(request)
  File "/Users/chengyinliu/anaconda3/lib/python3.7/site-packages/django/core/handlers/base.py", line 113, in _get_response
    resolver_match = resolver.resolve(request.path_info)
  File "/Users/chengyinliu/anaconda3/lib/python3.7/site-packages/django/urls/resolvers.py", line 527, in resolve
    raise Resolver404({'tried': tried, 'path': new_path})
django.urls.exceptions.Resolver404: {'tried': [[<URLResolver <URLPattern list> (admin:admin) 'admin/'>], [<URLResolver <module 'backend.version_1_0' from '/Users/chengyinliu/WeChatProjects/backend/backend/version_1_0.py'> (None:None) 'api/v1.0/'>]], 'path': 'all/rss/'}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/chengyinliu/anaconda3/lib/python3.7/site-packages/django/template/base.py", line 835, in _resolve_lookup
    current = current[bit]
TypeError: 'URLResolver' object is not subscriptable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/chengyinliu/anaconda3/lib/python3.7/site-packages/django/template/base.py", line 843, in _resolve_lookup
    current = getattr(current, bit)
AttributeError: 'URLResolver' object has no attribute 'name'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/chengyinliu/anaconda3/lib/python3.7/site-packages/django/template/base.py", line 849, in _resolve_lookup
    current = current[int(bit)]
ValueError: invalid literal for int() with base 10: 'name'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/chengyinliu/anaconda3/lib/python3.7/site-packages/django/template/base.py", line 856, in _resolve_lookup
    (bit, current))  # missing attribute
django.template.base.VariableDoesNotExist: Failed lookup for key [name] in <URLResolver <module 'backend.version_1_0' from '/Users/chengyinliu/WeChatProjects/backend/backend/version_1_0.py'> (None:None) 'api/v1.0/'>
2019-10-08 17:02:20,676 [Thread-2: 123145412268032]/Users/chengyinliu/anaconda3/lib/python3.7/site-packages/django/core/handlers/base.py:get_response:93 WARNING - Not Found: /all/rss/
2019-10-08 17:02:20,677 [Thread-2: 123145412268032]/Users/chengyinliu/anaconda3/lib/python3.7/site-packages/django/core/servers/basehttp.py:log_message:124 WARNING - "GET /all/rss/ HTTP/1.1" 404 2073
2019-10-08 17:11:56,418 [Dummy-1: 123145563967488]/Users/chengyinliu/anaconda3/lib/python3.7/site-packages/django/db/backends/utils.py:execute:111 DEBUG - (0.000) SELECT @@SQL_AUTO_IS_NULL; args=None
2019-10-08 17:11:56,419 [Dummy-1: 123145563967488]/Users/chengyinliu/anaconda3/lib/python3.7/site-packages/django/db/backends/utils.py:execute:111 DEBUG - (0.000) SET SESSION TRANSACTION ISOLATION LEVEL READ COMMITTED; args=None
2019-10-08 17:11:56,419 [Dummy-1: 123145563967488]/Users/chengyinliu/anaconda3/lib/python3.7/site-packages/django/db/backends/utils.py:execute:111 DEBUG - (0.000) SELECT VERSION(); args=None
2019-10-08 17:11:56,436 [Dummy-1: 123145563967488]/Users/chengyinliu/anaconda3/lib/python3.7/site-packages/django/db/backends/utils.py:execute:111 DEBUG - (0.000) SET SESSION TRANSACTION ISOLATION LEVEL READ COMMITTED; args=None
2019-10-08 17:11:56,437 [Dummy-1: 123145563967488]/Users/chengyinliu/anaconda3/lib/python3.7/site-packages/django/db/backends/utils.py:execute:111 DEBUG - (0.001) SHOW FULL TABLES; args=None
2019-10-08 17:11:56,439 [Dummy-1: 123145563967488]/Users/chengyinliu/anaconda3/lib/python3.7/site-packages/django/db/backends/utils.py:execute:111 DEBUG - (0.001) SELECT `django_migrations`.`app`, `django_migrations`.`name` FROM `django_migrations`; args=()
2019-10-08 17:11:56,443 [Dummy-1: 123145563967488]/Users/chengyinliu/WeChatProjects/backend/module/middleware.py:__init__:14 INFO - Build StatisticsMiddleware.
2019-10-08 17:12:17,487 [Dummy-1: 123145314390016]/Users/chengyinliu/anaconda3/lib/python3.7/site-packages/django/db/backends/utils.py:execute:111 DEBUG - (0.000) SELECT @@SQL_AUTO_IS_NULL; args=None
2019-10-08 17:12:17,488 [Dummy-1: 123145314390016]/Users/chengyinliu/anaconda3/lib/python3.7/site-packages/django/db/backends/utils.py:execute:111 DEBUG - (0.000) SET SESSION TRANSACTION ISOLATION LEVEL READ COMMITTED; args=None
2019-10-08 17:12:17,488 [Dummy-1: 123145314390016]/Users/chengyinliu/anaconda3/lib/python3.7/site-packages/django/db/backends/utils.py:execute:111 DEBUG - (0.000) SELECT VERSION(); args=None
2019-10-08 17:12:17,506 [Dummy-1: 123145314390016]/Users/chengyinliu/anaconda3/lib/python3.7/site-packages/django/db/backends/utils.py:execute:111 DEBUG - (0.000) SET SESSION TRANSACTION ISOLATION LEVEL READ COMMITTED; args=None
2019-10-08 17:12:17,507 [Dummy-1: 123145314390016]/Users/chengyinliu/anaconda3/lib/python3.7/site-packages/django/db/backends/utils.py:execute:111 DEBUG - (0.001) SHOW FULL TABLES; args=None
2019-10-08 17:12:17,509 [Dummy-1: 123145314390016]/Users/chengyinliu/anaconda3/lib/python3.7/site-packages/django/db/backends/utils.py:execute:111 DEBUG - (0.001) SELECT `django_migrations`.`app`, `django_migrations`.`name` FROM `django_migrations`; args=()
2019-10-08 17:12:17,513 [Dummy-1: 123145314390016]/Users/chengyinliu/WeChatProjects/backend/module/middleware.py:__init__:14 INFO - Build StatisticsMiddleware.
2019-10-08 17:12:20,692 [Thread-2: 123145319645184]/Users/chengyinliu/anaconda3/lib/python3.7/site-packages/django/template/base.py:_resolve_lookup:878 DEBUG - Exception while resolving variable 'name' in template 'unknown'.
Traceback (most recent call last):
  File "/Users/chengyinliu/anaconda3/lib/python3.7/site-packages/django/core/handlers/exception.py", line 35, in inner
    response = get_response(request)
  File "/Users/chengyinliu/anaconda3/lib/python3.7/site-packages/django/core/handlers/base.py", line 113, in _get_response
    resolver_match = resolver.resolve(request.path_info)
  File "/Users/chengyinliu/anaconda3/lib/python3.7/site-packages/django/urls/resolvers.py", line 527, in resolve
    raise Resolver404({'tried': tried, 'path': new_path})
django.urls.exceptions.Resolver404: {'tried': [[<URLResolver <URLPattern list> (admin:admin) 'admin/'>], [<URLResolver <module 'backend.version_1_0' from '/Users/chengyinliu/WeChatProjects/backend/backend/version_1_0.py'> (None:None) 'api/v1.0/'>]], 'path': 'all/rss/'}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/chengyinliu/anaconda3/lib/python3.7/site-packages/django/template/base.py", line 835, in _resolve_lookup
    current = current[bit]
TypeError: 'URLResolver' object is not subscriptable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/chengyinliu/anaconda3/lib/python3.7/site-packages/django/template/base.py", line 843, in _resolve_lookup
    current = getattr(current, bit)
AttributeError: 'URLResolver' object has no attribute 'name'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/chengyinliu/anaconda3/lib/python3.7/site-packages/django/template/base.py", line 849, in _resolve_lookup
    current = current[int(bit)]
ValueError: invalid literal for int() with base 10: 'name'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/chengyinliu/anaconda3/lib/python3.7/site-packages/django/template/base.py", line 856, in _resolve_lookup
    (bit, current))  # missing attribute
django.template.base.VariableDoesNotExist: Failed lookup for key [name] in <URLResolver <URLPattern list> (admin:admin) 'admin/'>
2019-10-08 17:12:20,693 [Thread-2: 123145319645184]/Users/chengyinliu/anaconda3/lib/python3.7/site-packages/django/template/base.py:_resolve_lookup:878 DEBUG - Exception while resolving variable 'name' in template 'unknown'.
Traceback (most recent call last):
  File "/Users/chengyinliu/anaconda3/lib/python3.7/site-packages/django/core/handlers/exception.py", line 35, in inner
    response = get_response(request)
  File "/Users/chengyinliu/anaconda3/lib/python3.7/site-packages/django/core/handlers/base.py", line 113, in _get_response
    resolver_match = resolver.resolve(request.path_info)
  File "/Users/chengyinliu/anaconda3/lib/python3.7/site-packages/django/urls/resolvers.py", line 527, in resolve
    raise Resolver404({'tried': tried, 'path': new_path})
django.urls.exceptions.Resolver404: {'tried': [[<URLResolver <URLPattern list> (admin:admin) 'admin/'>], [<URLResolver <module 'backend.version_1_0' from '/Users/chengyinliu/WeChatProjects/backend/backend/version_1_0.py'> (None:None) 'api/v1.0/'>]], 'path': 'all/rss/'}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/chengyinliu/anaconda3/lib/python3.7/site-packages/django/template/base.py", line 835, in _resolve_lookup
    current = current[bit]
TypeError: 'URLResolver' object is not subscriptable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/chengyinliu/anaconda3/lib/python3.7/site-packages/django/template/base.py", line 843, in _resolve_lookup
    current = getattr(current, bit)
AttributeError: 'URLResolver' object has no attribute 'name'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/chengyinliu/anaconda3/lib/python3.7/site-packages/django/template/base.py", line 849, in _resolve_lookup
    current = current[int(bit)]
ValueError: invalid literal for int() with base 10: 'name'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/chengyinliu/anaconda3/lib/python3.7/site-packages/django/template/base.py", line 856, in _resolve_lookup
    (bit, current))  # missing attribute
django.template.base.VariableDoesNotExist: Failed lookup for key [name] in <URLResolver <module 'backend.version_1_0' from '/Users/chengyinliu/WeChatProjects/backend/backend/version_1_0.py'> (None:None) 'api/v1.0/'>
2019-10-08 17:12:20,694 [Thread-2: 123145319645184]/Users/chengyinliu/anaconda3/lib/python3.7/site-packages/django/core/handlers/base.py:get_response:93 WARNING - Not Found: /all/rss/
2019-10-08 17:12:20,694 [Thread-2: 123145319645184]/Users/chengyinliu/anaconda3/lib/python3.7/site-packages/django/core/servers/basehttp.py:log_message:124 WARNING - "GET /all/rss/ HTTP/1.1" 404 2073
2019-10-08 17:12:59,055 [Thread-3: 123145319645184]/Users/chengyinliu/anaconda3/lib/python3.7/site-packages/django/core/servers/basehttp.py:log_message:124 INFO - "GET /api/v1.0/service/test HTTP/1.1" 200 11
2019-10-08 17:12:59,060 [Thread-4: 123145319645184]/Users/chengyinliu/anaconda3/lib/python3.7/site-packages/django/core/servers/basehttp.py:log_message:124 INFO - "GET /api/v1.0/service/image/list HTTP/1.1" 200 143
2019-10-08 17:13:00,068 [Thread-5: 123145319645184]/Users/chengyinliu/anaconda3/lib/python3.7/site-packages/django/core/servers/basehttp.py:log_message:124 INFO - "GET /api/v1.0/service/test HTTP/1.1" 200 11
2019-10-08 17:13:00,074 [Thread-6: 123145319645184]/Users/chengyinliu/anaconda3/lib/python3.7/site-packages/django/core/servers/basehttp.py:log_message:124 INFO - "GET /api/v1.0/service/image/list HTTP/1.1" 200 143
2019-10-08 17:13:01,087 [Thread-7: 123145319645184]/Users/chengyinliu/anaconda3/lib/python3.7/site-packages/django/core/servers/basehttp.py:log_message:124 INFO - "GET /api/v1.0/service/test HTTP/1.1" 200 11
2019-10-08 17:13:01,091 [Thread-8: 123145319645184]/Users/chengyinliu/anaconda3/lib/python3.7/site-packages/django/core/servers/basehttp.py:log_message:124 INFO - "GET /api/v1.0/service/image/list HTTP/1.1" 200 143
2019-10-08 17:13:02,102 [Thread-9: 123145319645184]/Users/chengyinliu/anaconda3/lib/python3.7/site-packages/django/core/servers/basehttp.py:log_message:124 INFO - "GET /api/v1.0/service/test HTTP/1.1" 200 11
2019-10-08 17:13:02,106 [Thread-10: 123145319645184]/Users/chengyinliu/anaconda3/lib/python3.7/site-packages/django/core/servers/basehttp.py:log_message:124 INFO - "GET /api/v1.0/service/image/list HTTP/1.1" 200 143
2019-10-08 17:13:03,118 [Thread-11: 123145319645184]/Users/chengyinliu/anaconda3/lib/python3.7/site-packages/django/core/servers/basehttp.py:log_message:124 INFO - "GET /api/v1.0/service/test HTTP/1.1" 200 11
2019-10-08 17:13:03,124 [Thread-12: 123145319645184]/Users/chengyinliu/anaconda3/lib/python3.7/site-packages/django/core/servers/basehttp.py:log_message:124 INFO - "GET /api/v1.0/service/image/list HTTP/1.1" 200 143
2019-10-08 17:13:04,132 [Thread-13: 123145319645184]/Users/chengyinliu/anaconda3/lib/python3.7/site-packages/django/core/servers/basehttp.py:log_message:124 INFO - "GET /api/v1.0/service/test HTTP/1.1" 200 11
2019-10-08 17:13:04,138 [Thread-14: 123145319645184]/Users/chengyinliu/anaconda3/lib/python3.7/site-packages/django/core/servers/basehttp.py:log_message:124 INFO - "GET /api/v1.0/service/image/list HTTP/1.1" 200 143
2019-10-08 17:13:05,150 [Thread-15: 123145319645184]/Users/chengyinliu/anaconda3/lib/python3.7/site-packages/django/core/servers/basehttp.py:log_message:124 INFO - "GET /api/v1.0/service/test HTTP/1.1" 200 11
2019-10-08 17:13:05,155 [Thread-16: 123145319645184]/Users/chengyinliu/anaconda3/lib/python3.7/site-packages/django/core/servers/basehttp.py:log_message:124 INFO - "GET /api/v1.0/service/image/list HTTP/1.1" 200 143
2019-10-08 17:13:06,167 [Thread-17: 123145319645184]/Users/chengyinliu/anaconda3/lib/python3.7/site-packages/django/core/servers/basehttp.py:log_message:124 INFO - "GET /api/v1.0/service/test HTTP/1.1" 200 11
2019-10-08 17:13:06,173 [Thread-18: 123145319645184]/Users/chengyinliu/anaconda3/lib/python3.7/site-packages/django/core/servers/basehttp.py:log_message:124 INFO - "GET /api/v1.0/service/image/list HTTP/1.1" 200 143
2019-10-08 17:13:07,185 [Thread-19: 123145319645184]/Users/chengyinliu/anaconda3/lib/python3.7/site-packages/django/core/servers/basehttp.py:log_message:124 INFO - "GET /api/v1.0/service/test HTTP/1.1" 200 11
2019-10-08 17:13:07,190 [Thread-20: 123145319645184]/Users/chengyinliu/anaconda3/lib/python3.7/site-packages/django/core/servers/basehttp.py:log_message:124 INFO - "GET /api/v1.0/service/image/list HTTP/1.1" 200 143
2019-10-08 17:13:08,202 [Thread-21: 123145319645184]/Users/chengyinliu/anaconda3/lib/python3.7/site-packages/django/core/servers/basehttp.py:log_message:124 INFO - "GET /api/v1.0/service/test HTTP/1.1" 200 11
2019-10-08 17:13:08,207 [Thread-22: 123145319645184]/Users/chengyinliu/anaconda3/lib/python3.7/site-packages/django/core/servers/basehttp.py:log_message:124 INFO - "GET /api/v1.0/service/image/list HTTP/1.1" 200 143
2019-10-08 17:13:09,217 [Thread-23: 123145319645184]/Users/chengyinliu/anaconda3/lib/python3.7/site-packages/django/core/servers/basehttp.py:log_message:124 INFO - "GET /api/v1.0/service/test HTTP/1.1" 200 11
2019-10-08 17:13:09,221 [Thread-24: 123145319645184]/Users/chengyinliu/anaconda3/lib/python3.7/site-packages/django/core/servers/basehttp.py:log_message:124 INFO - "GET /api/v1.0/service/image/list HTTP/1.1" 200 143
2019-10-08 17:13:10,235 [Thread-25: 123145319645184]/Users/chengyinliu/anaconda3/lib/python3.7/site-packages/django/core/servers/basehttp.py:log_message:124 INFO - "GET /api/v1.0/service/test HTTP/1.1" 200 11
2019-10-08 17:13:10,240 [Thread-26: 123145319645184]/Users/chengyinliu/anaconda3/lib/python3.7/site-packages/django/core/servers/basehttp.py:log_message:124 INFO - "GET /api/v1.0/service/image/list HTTP/1.1" 200 143
2019-10-08 17:13:11,248 [Thread-27: 123145319645184]/Users/chengyinliu/anaconda3/lib/python3.7/site-packages/django/core/servers/basehttp.py:log_message:124 INFO - "GET /api/v1.0/service/test HTTP/1.1" 200 11
2019-10-08 17:13:11,253 [Thread-28: 123145319645184]/Users/chengyinliu/anaconda3/lib/python3.7/site-packages/django/core/servers/basehttp.py:log_message:124 INFO - "GET /api/v1.0/service/image/list HTTP/1.1" 200 143
2019-10-08 17:13:12,265 [Thread-29: 123145319645184]/Users/chengyinliu/anaconda3/lib/python3.7/site-packages/django/core/servers/basehttp.py:log_message:124 INFO - "GET /api/v1.0/service/test HTTP/1.1" 200 11
2019-10-08 17:13:12,271 [Thread-30: 123145319645184]/Users/chengyinliu/anaconda3/lib/python3.7/site-packages/django/core/servers/basehttp.py:log_message:124 INFO - "GET /api/v1.0/service/image/list HTTP/1.1" 200 143
2019-10-08 17:13:13,279 [Thread-31: 123145319645184]/Users/chengyinliu/anaconda3/lib/python3.7/site-packages/django/core/servers/basehttp.py:log_message:124 INFO - "GET /api/v1.0/service/test HTTP/1.1" 200 11
2019-10-08 17:13:13,283 [Thread-32: 123145319645184]/Users/chengyinliu/anaconda3/lib/python3.7/site-packages/django/core/servers/basehttp.py:log_message:124 INFO - "GET /api/v1.0/service/image/list HTTP/1.1" 200 143
2019-10-08 17:13:14,293 [Thread-33: 123145319645184]/Users/chengyinliu/anaconda3/lib/python3.7/site-packages/django/core/servers/basehttp.py:log_message:124 INFO - "GET /api/v1.0/service/test HTTP/1.1" 200 11
2019-10-08 17:13:14,298 [Thread-34: 123145319645184]/Users/chengyinliu/anaconda3/lib/python3.7/site-packages/django/core/servers/basehttp.py:log_message:124 INFO - "GET /api/v1.0/service/image/list HTTP/1.1" 200 143
2019-10-08 17:13:15,310 [Thread-35: 123145319645184]/Users/chengyinliu/anaconda3/lib/python3.7/site-packages/django/core/servers/basehttp.py:log_message:124 INFO - "GET /api/v1.0/service/test HTTP/1.1" 200 11
2019-10-08 17:13:15,315 [Thread-36: 123145319645184]/Users/chengyinliu/anaconda3/lib/python3.7/site-packages/django/core/servers/basehttp.py:log_message:124 INFO - "GET /api/v1.0/service/image/list HTTP/1.1" 200 143
2019-10-08 17:13:16,324 [Thread-37: 123145319645184]/Users/chengyinliu/anaconda3/lib/python3.7/site-packages/django/core/servers/basehttp.py:log_message:124 INFO - "GET /api/v1.0/service/test HTTP/1.1" 200 11
2019-10-08 17:13:16,329 [Thread-38: 123145319645184]/Users/chengyinliu/anaconda3/lib/python3.7/site-packages/django/core/servers/basehttp.py:log_message:124 INFO - "GET /api/v1.0/service/image/list HTTP/1.1" 200 143
2019-10-08 17:13:17,336 [Thread-39: 123145319645184]/Users/chengyinliu/anaconda3/lib/python3.7/site-packages/django/core/servers/basehttp.py:log_message:124 INFO - "GET /api/v1.0/service/test HTTP/1.1" 200 11
2019-10-08 17:13:17,339 [Thread-40: 123145319645184]/Users/chengyinliu/anaconda3/lib/python3.7/site-packages/django/core/servers/basehttp.py:log_message:124 INFO - "GET /api/v1.0/service/image/list HTTP/1.1" 200 143
2019-10-08 17:13:18,348 [Thread-41: 123145319645184]/Users/chengyinliu/anaconda3/lib/python3.7/site-packages/django/core/servers/basehttp.py:log_message:124 INFO - "GET /api/v1.0/service/test HTTP/1.1" 200 11
2019-10-08 17:13:18,353 [Thread-42: 123145319645184]/Users/chengyinliu/anaconda3/lib/python3.7/site-packages/django/core/servers/basehttp.py:log_message:124 INFO - "GET /api/v1.0/service/image/list HTTP/1.1" 200 143
2019-10-08 17:13:19,362 [Thread-43: 123145319645184]/Users/chengyinliu/anaconda3/lib/python3.7/site-packages/django/core/servers/basehttp.py:log_message:124 INFO - "GET /api/v1.0/service/test HTTP/1.1" 200 11
2019-10-08 17:13:19,367 [Thread-44: 123145319645184]/Users/chengyinliu/anaconda3/lib/python3.7/site-packages/django/core/servers/basehttp.py:log_message:124 INFO - "GET /api/v1.0/service/image/list HTTP/1.1" 200 143
2019-10-08 17:13:20,377 [Thread-45: 123145319645184]/Users/chengyinliu/anaconda3/lib/python3.7/site-packages/django/core/servers/basehttp.py:log_message:124 INFO - "GET /api/v1.0/service/test HTTP/1.1" 200 11
2019-10-08 17:13:20,383 [Thread-46: 123145319645184]/Users/chengyinliu/anaconda3/lib/python3.7/site-packages/django/core/servers/basehttp.py:log_message:124 INFO - "GET /api/v1.0/service/image/list HTTP/1.1" 200 143
2019-10-08 17:13:21,396 [Thread-47: 123145319645184]/Users/chengyinliu/anaconda3/lib/python3.7/site-packages/django/core/servers/basehttp.py:log_message:124 INFO - "GET /api/v1.0/service/test HTTP/1.1" 200 11
2019-10-08 17:13:21,402 [Thread-48: 123145319645184]/Users/chengyinliu/anaconda3/lib/python3.7/site-packages/django/core/servers/basehttp.py:log_message:124 INFO - "GET /api/v1.0/service/image/list HTTP/1.1" 200 143
2019-10-08 17:13:22,412 [Thread-49: 123145319645184]/Users/chengyinliu/anaconda3/lib/python3.7/site-packages/django/core/servers/basehttp.py:log_message:124 INFO - "GET /api/v1.0/service/test HTTP/1.1" 200 11
2019-10-08 17:13:22,418 [Thread-50: 123145319645184]/Users/chengyinliu/anaconda3/lib/python3.7/site-packages/django/core/servers/basehttp.py:log_message:124 INFO - "GET /api/v1.0/service/image/list HTTP/1.1" 200 143
2019-10-08 17:13:23,430 [Thread-51: 123145319645184]/Users/chengyinliu/anaconda3/lib/python3.7/site-packages/django/core/servers/basehttp.py:log_message:124 INFO - "GET /api/v1.0/service/test HTTP/1.1" 200 11
2019-10-08 17:13:23,435 [Thread-52: 123145319645184]/Users/chengyinliu/anaconda3/lib/python3.7/site-packages/django/core/servers/basehttp.py:log_message:124 INFO - "GET /api/v1.0/service/image/list HTTP/1.1" 200 143
2019-10-08 17:13:24,443 [Thread-53: 123145319645184]/Users/chengyinliu/anaconda3/lib/python3.7/site-packages/django/core/servers/basehttp.py:log_message:124 INFO - "GET /api/v1.0/service/test HTTP/1.1" 200 11
2019-10-08 17:13:24,449 [Thread-54: 123145319645184]/Users/chengyinliu/anaconda3/lib/python3.7/site-packages/django/core/servers/basehttp.py:log_message:124 INFO - "GET /api/v1.0/service/image/list HTTP/1.1" 200 143
2019-10-08 17:13:25,460 [Thread-55: 123145319645184]/Users/chengyinliu/anaconda3/lib/python3.7/site-packages/django/core/servers/basehttp.py:log_message:124 INFO - "GET /api/v1.0/service/test HTTP/1.1" 200 11
2019-10-08 17:13:25,466 [Thread-56: 123145319645184]/Users/chengyinliu/anaconda3/lib/python3.7/site-packages/django/core/servers/basehttp.py:log_message:124 INFO - "GET /api/v1.0/service/image/list HTTP/1.1" 200 143
2019-10-08 17:13:26,478 [Thread-57: 123145319645184]/Users/chengyinliu/anaconda3/lib/python3.7/site-packages/django/core/servers/basehttp.py:log_message:124 INFO - "GET /api/v1.0/service/test HTTP/1.1" 200 11
2019-10-08 17:13:26,484 [Thread-58: 123145319645184]/Users/chengyinliu/anaconda3/lib/python3.7/site-packages/django/core/servers/basehttp.py:log_message:124 INFO - "GET /api/v1.0/service/image/list HTTP/1.1" 200 143
2019-10-08 17:13:27,495 [Thread-59: 123145319645184]/Users/chengyinliu/anaconda3/lib/python3.7/site-packages/django/core/servers/basehttp.py:log_message:124 INFO - "GET /api/v1.0/service/test HTTP/1.1" 200 11
2019-10-08 17:13:27,502 [Thread-60: 123145319645184]/Users/chengyinliu/anaconda3/lib/python3.7/site-packages/django/core/servers/basehttp.py:log_message:124 INFO - "GET /api/v1.0/service/image/list HTTP/1.1" 200 143
2019-10-08 17:13:28,513 [Thread-61: 123145319645184]/Users/chengyinliu/anaconda3/lib/python3.7/site-packages/django/core/servers/basehttp.py:log_message:124 INFO - "GET /api/v1.0/service/test HTTP/1.1" 200 11
2019-10-08 17:13:28,519 [Thread-62: 123145319645184]/Users/chengyinliu/anaconda3/lib/python3.7/site-packages/django/core/servers/basehttp.py:log_message:124 INFO - "GET /api/v1.0/service/image/list HTTP/1.1" 200 143
2019-10-08 17:13:29,530 [Thread-63: 123145319645184]/Users/chengyinliu/anaconda3/lib/python3.7/site-packages/django/core/servers/basehttp.py:log_message:124 INFO - "GET /api/v1.0/service/test HTTP/1.1" 200 11
2019-10-08 17:13:29,535 [Thread-64: 123145319645184]/Users/chengyinliu/anaconda3/lib/python3.7/site-packages/django/core/servers/basehttp.py:log_message:124 INFO - "GET /api/v1.0/service/image/list HTTP/1.1" 200 143
2019-10-08 17:13:30,542 [Thread-65: 123145319645184]/Users/chengyinliu/anaconda3/lib/python3.7/site-packages/django/core/servers/basehttp.py:log_message:124 INFO - "GET /api/v1.0/service/test HTTP/1.1" 200 11
2019-10-08 17:13:30,546 [Thread-66: 123145319645184]/Users/chengyinliu/anaconda3/lib/python3.7/site-packages/django/core/servers/basehttp.py:log_message:124 INFO - "GET /api/v1.0/service/image/list HTTP/1.1" 200 143
2019-10-08 17:13:31,557 [Thread-67: 123145319645184]/Users/chengyinliu/anaconda3/lib/python3.7/site-packages/django/core/servers/basehttp.py:log_message:124 INFO - "GET /api/v1.0/service/test HTTP/1.1" 200 11
2019-10-08 17:13:31,562 [Thread-68: 123145319645184]/Users/chengyinliu/anaconda3/lib/python3.7/site-packages/django/core/servers/basehttp.py:log_message:124 INFO - "GET /api/v1.0/service/image/list HTTP/1.1" 200 143
2019-10-08 17:13:32,575 [Thread-69: 123145319645184]/Users/chengyinliu/anaconda3/lib/python3.7/site-packages/django/core/servers/basehttp.py:log_message:124 INFO - "GET /api/v1.0/service/test HTTP/1.1" 200 11
2019-10-08 17:13:32,581 [Thread-70: 123145319645184]/Users/chengyinliu/anaconda3/lib/python3.7/site-packages/django/core/servers/basehttp.py:log_message:124 INFO - "GET /api/v1.0/service/image/list HTTP/1.1" 200 143
2019-10-08 17:13:33,592 [Thread-71: 123145319645184]/Users/chengyinliu/anaconda3/lib/python3.7/site-packages/django/core/servers/basehttp.py:log_message:124 INFO - "GET /api/v1.0/service/test HTTP/1.1" 200 11
2019-10-08 17:13:33,598 [Thread-72: 123145319645184]/Users/chengyinliu/anaconda3/lib/python3.7/site-packages/django/core/servers/basehttp.py:log_message:124 INFO - "GET /api/v1.0/service/image/list HTTP/1.1" 200 143
2019-10-08 17:13:34,609 [Thread-73: 123145319645184]/Users/chengyinliu/anaconda3/lib/python3.7/site-packages/django/core/servers/basehttp.py:log_message:124 INFO - "GET /api/v1.0/service/test HTTP/1.1" 200 11
2019-10-08 17:13:34,615 [Thread-74: 123145319645184]/Users/chengyinliu/anaconda3/lib/python3.7/site-packages/django/core/servers/basehttp.py:log_message:124 INFO - "GET /api/v1.0/service/image/list HTTP/1.1" 200 143
2019-10-08 17:13:35,624 [Thread-75: 123145319645184]/Users/chengyinliu/anaconda3/lib/python3.7/site-packages/django/core/servers/basehttp.py:log_message:124 INFO - "GET /api/v1.0/service/test HTTP/1.1" 200 11
2019-10-08 17:13:35,629 [Thread-76: 123145319645184]/Users/chengyinliu/anaconda3/lib/python3.7/site-packages/django/core/servers/basehttp.py:log_message:124 INFO - "GET /api/v1.0/service/image/list HTTP/1.1" 200 143
2019-10-08 17:13:36,638 [Thread-77: 123145319645184]/Users/chengyinliu/anaconda3/lib/python3.7/site-packages/django/core/servers/basehttp.py:log_message:124 INFO - "GET /api/v1.0/service/test HTTP/1.1" 200 11
2019-10-08 17:13:36,644 [Thread-78: 123145319645184]/Users/chengyinliu/anaconda3/lib/python3.7/site-packages/django/core/servers/basehttp.py:log_message:124 INFO - "GET /api/v1.0/service/image/list HTTP/1.1" 200 143
2019-10-08 17:13:37,654 [Thread-79: 123145319645184]/Users/chengyinliu/anaconda3/lib/python3.7/site-packages/django/core/servers/basehttp.py:log_message:124 INFO - "GET /api/v1.0/service/test HTTP/1.1" 200 11
2019-10-08 17:13:37,660 [Thread-80: 123145319645184]/Users/chengyinliu/anaconda3/lib/python3.7/site-packages/django/core/servers/basehttp.py:log_message:124 INFO - "GET /api/v1.0/service/image/list HTTP/1.1" 200 143
2019-10-08 17:13:38,671 [Thread-81: 123145319645184]/Users/chengyinliu/anaconda3/lib/python3.7/site-packages/django/core/servers/basehttp.py:log_message:124 INFO - "GET /api/v1.0/service/test HTTP/1.1" 200 11
2019-10-08 17:13:38,676 [Thread-82: 123145319645184]/Users/chengyinliu/anaconda3/lib/python3.7/site-packages/django/core/servers/basehttp.py:log_message:124 INFO - "GET /api/v1.0/service/image/list HTTP/1.1" 200 143
2019-10-08 17:13:39,681 [Thread-83: 123145319645184]/Users/chengyinliu/anaconda3/lib/python3.7/site-packages/django/core/servers/basehttp.py:log_message:124 INFO - "GET /api/v1.0/service/test HTTP/1.1" 200 11
2019-10-08 17:13:39,685 [Thread-84: 123145319645184]/Users/chengyinliu/anaconda3/lib/python3.7/site-packages/django/core/servers/basehttp.py:log_message:124 INFO - "GET /api/v1.0/service/image/list HTTP/1.1" 200 143
2019-10-08 17:13:40,693 [Thread-85: 123145319645184]/Users/chengyinliu/anaconda3/lib/python3.7/site-packages/django/core/servers/basehttp.py:log_message:124 INFO - "GET /api/v1.0/service/test HTTP/1.1" 200 11
2019-10-08 17:13:40,699 [Thread-86: 123145319645184]/Users/chengyinliu/anaconda3/lib/python3.7/site-packages/django/core/servers/basehttp.py:log_message:124 INFO - "GET /api/v1.0/service/image/list HTTP/1.1" 200 143
2019-10-08 17:13:41,709 [Thread-87: 123145319645184]/Users/chengyinliu/anaconda3/lib/python3.7/site-packages/django/core/servers/basehttp.py:log_message:124 INFO - "GET /api/v1.0/service/test HTTP/1.1" 200 11
2019-10-08 17:13:41,715 [Thread-88: 123145319645184]/Users/chengyinliu/anaconda3/lib/python3.7/site-packages/django/core/servers/basehttp.py:log_message:124 INFO - "GET /api/v1.0/service/image/list HTTP/1.1" 200 143
2019-10-08 17:13:42,725 [Thread-89: 123145319645184]/Users/chengyinliu/anaconda3/lib/python3.7/site-packages/django/core/servers/basehttp.py:log_message:124 INFO - "GET /api/v1.0/service/test HTTP/1.1" 200 11
2019-10-08 17:13:42,731 [Thread-90: 123145319645184]/Users/chengyinliu/anaconda3/lib/python3.7/site-packages/django/core/servers/basehttp.py:log_message:124 INFO - "GET /api/v1.0/service/image/list HTTP/1.1" 200 143
2019-10-08 17:13:43,743 [Thread-91: 123145319645184]/Users/chengyinliu/anaconda3/lib/python3.7/site-packages/django/core/servers/basehttp.py:log_message:124 INFO - "GET /api/v1.0/service/test HTTP/1.1" 200 11
2019-10-08 17:13:43,749 [Thread-92: 123145319645184]/Users/chengyinliu/anaconda3/lib/python3.7/site-packages/django/core/servers/basehttp.py:log_message:124 INFO - "GET /api/v1.0/service/image/list HTTP/1.1" 200 143
2019-10-08 17:13:44,758 [Thread-93: 123145319645184]/Users/chengyinliu/anaconda3/lib/python3.7/site-packages/django/core/servers/basehttp.py:log_message:124 INFO - "GET /api/v1.0/service/test HTTP/1.1" 200 11
2019-10-08 17:13:44,762 [Thread-94: 123145319645184]/Users/chengyinliu/anaconda3/lib/python3.7/site-packages/django/core/servers/basehttp.py:log_message:124 INFO - "GET /api/v1.0/service/image/list HTTP/1.1" 200 143
2019-10-08 17:13:45,774 [Thread-95: 123145319645184]/Users/chengyinliu/anaconda3/lib/python3.7/site-packages/django/core/servers/basehttp.py:log_message:124 INFO - "GET /api/v1.0/service/test HTTP/1.1" 200 11
2019-10-08 17:13:45,780 [Thread-96: 123145319645184]/Users/chengyinliu/anaconda3/lib/python3.7/site-packages/django/core/servers/basehttp.py:log_message:124 INFO - "GET /api/v1.0/service/image/list HTTP/1.1" 200 143
2019-10-08 17:13:46,792 [Thread-97: 123145319645184]/Users/chengyinliu/anaconda3/lib/python3.7/site-packages/django/core/servers/basehttp.py:log_message:124 INFO - "GET /api/v1.0/service/test HTTP/1.1" 200 11
2019-10-08 17:13:46,797 [Thread-98: 123145319645184]/Users/chengyinliu/anaconda3/lib/python3.7/site-packages/django/core/servers/basehttp.py:log_message:124 INFO - "GET /api/v1.0/service/image/list HTTP/1.1" 200 143
2019-10-08 17:13:47,805 [Thread-99: 123145319645184]/Users/chengyinliu/anaconda3/lib/python3.7/site-packages/django/core/servers/basehttp.py:log_message:124 INFO - "GET /api/v1.0/service/test HTTP/1.1" 200 11
2019-10-08 17:13:47,811 [Thread-100: 123145319645184]/Users/chengyinliu/anaconda3/lib/python3.7/site-packages/django/core/servers/basehttp.py:log_message:124 INFO - "GET /api/v1.0/service/image/list HTTP/1.1" 200 143
2019-10-08 17:13:48,823 [Thread-101: 123145319645184]/Users/chengyinliu/anaconda3/lib/python3.7/site-packages/django/core/servers/basehttp.py:log_message:124 INFO - "GET /api/v1.0/service/test HTTP/1.1" 200 11
2019-10-08 17:13:48,828 [Thread-102: 123145319645184]/Users/chengyinliu/anaconda3/lib/python3.7/site-packages/django/core/servers/basehttp.py:log_message:124 INFO - "GET /api/v1.0/service/image/list HTTP/1.1" 200 143
2019-10-08 17:13:49,841 [Thread-103: 123145319645184]/Users/chengyinliu/anaconda3/lib/python3.7/site-packages/django/core/servers/basehttp.py:log_message:124 INFO - "GET /api/v1.0/service/test HTTP/1.1" 200 11
2019-10-08 17:13:49,846 [Thread-104: 123145319645184]/Users/chengyinliu/anaconda3/lib/python3.7/site-packages/django/core/servers/basehttp.py:log_message:124 INFO - "GET /api/v1.0/service/image/list HTTP/1.1" 200 143
2019-10-08 17:13:50,853 [Thread-105: 123145319645184]/Users/chengyinliu/anaconda3/lib/python3.7/site-packages/django/core/servers/basehttp.py:log_message:124 INFO - "GET /api/v1.0/service/test HTTP/1.1" 200 11
2019-10-08 17:13:50,858 [Thread-106: 123145319645184]/Users/chengyinliu/anaconda3/lib/python3.7/site-packages/django/core/servers/basehttp.py:log_message:124 INFO - "GET /api/v1.0/service/image/list HTTP/1.1" 200 143
2019-10-08 17:13:51,866 [Thread-107: 123145319645184]/Users/chengyinliu/anaconda3/lib/python3.7/site-packages/django/core/servers/basehttp.py:log_message:124 INFO - "GET /api/v1.0/service/test HTTP/1.1" 200 11
2019-10-08 17:13:51,873 [Thread-108: 123145319645184]/Users/chengyinliu/anaconda3/lib/python3.7/site-packages/django/core/servers/basehttp.py:log_message:124 INFO - "GET /api/v1.0/service/image/list HTTP/1.1" 200 143
2019-10-08 17:13:52,884 [Thread-109: 123145319645184]/Users/chengyinliu/anaconda3/lib/python3.7/site-packages/django/core/servers/basehttp.py:log_message:124 INFO - "GET /api/v1.0/service/test HTTP/1.1" 200 11
2019-10-08 17:13:52,890 [Thread-110: 123145319645184]/Users/chengyinliu/anaconda3/lib/python3.7/site-packages/django/core/servers/basehttp.py:log_message:124 INFO - "GET /api/v1.0/service/image/list HTTP/1.1" 200 143
2019-10-08 17:13:53,899 [Thread-111: 123145319645184]/Users/chengyinliu/anaconda3/lib/python3.7/site-packages/django/core/servers/basehttp.py:log_message:124 INFO - "GET /api/v1.0/service/test HTTP/1.1" 200 11
2019-10-08 17:13:53,904 [Thread-112: 123145319645184]/Users/chengyinliu/anaconda3/lib/python3.7/site-packages/django/core/servers/basehttp.py:log_message:124 INFO - "GET /api/v1.0/service/image/list HTTP/1.1" 200 143
2019-10-08 17:13:54,911 [Thread-113: 123145319645184]/Users/chengyinliu/anaconda3/lib/python3.7/site-packages/django/core/servers/basehttp.py:log_message:124 INFO - "GET /api/v1.0/service/test HTTP/1.1" 200 11
2019-10-08 17:13:54,916 [Thread-114: 123145319645184]/Users/chengyinliu/anaconda3/lib/python3.7/site-packages/django/core/servers/basehttp.py:log_message:124 INFO - "GET /api/v1.0/service/image/list HTTP/1.1" 200 143
2019-10-08 17:13:55,927 [Thread-115: 123145319645184]/Users/chengyinliu/anaconda3/lib/python3.7/site-packages/django/core/servers/basehttp.py:log_message:124 INFO - "GET /api/v1.0/service/test HTTP/1.1" 200 11
2019-10-08 17:13:55,932 [Thread-116: 123145319645184]/Users/chengyinliu/anaconda3/lib/python3.7/site-packages/django/core/servers/basehttp.py:log_message:124 INFO - "GET /api/v1.0/service/image/list HTTP/1.1" 200 143
2019-10-08 17:13:56,941 [Thread-117: 123145319645184]/Users/chengyinliu/anaconda3/lib/python3.7/site-packages/django/core/servers/basehttp.py:log_message:124 INFO - "GET /api/v1.0/service/test HTTP/1.1" 200 11
2019-10-08 17:13:56,947 [Thread-118: 123145319645184]/Users/chengyinliu/anaconda3/lib/python3.7/site-packages/django/core/servers/basehttp.py:log_message:124 INFO - "GET /api/v1.0/service/image/list HTTP/1.1" 200 143
2019-10-08 17:13:57,958 [Thread-119: 123145319645184]/Users/chengyinliu/anaconda3/lib/python3.7/site-packages/django/core/servers/basehttp.py:log_message:124 INFO - "GET /api/v1.0/service/test HTTP/1.1" 200 11
2019-10-08 17:13:57,963 [Thread-120: 123145319645184]/Users/chengyinliu/anaconda3/lib/python3.7/site-packages/django/core/servers/basehttp.py:log_message:124 INFO - "GET /api/v1.0/service/image/list HTTP/1.1" 200 143
2019-10-08 17:13:58,976 [Thread-121: 123145319645184]/Users/chengyinliu/anaconda3/lib/python3.7/site-packages/django/core/servers/basehttp.py:log_message:124 INFO - "GET /api/v1.0/service/test HTTP/1.1" 200 11
2019-10-08 17:13:58,981 [Thread-122: 123145319645184]/Users/chengyinliu/anaconda3/lib/python3.7/site-packages/django/core/servers/basehttp.py:log_message:124 INFO - "GET /api/v1.0/service/image/list HTTP/1.1" 200 143
2019-10-08 17:13:59,992 [Thread-123: 123145319645184]/Users/chengyinliu/anaconda3/lib/python3.7/site-packages/django/core/servers/basehttp.py:log_message:124 INFO - "GET /api/v1.0/service/test HTTP/1.1" 200 11
2019-10-08 17:13:59,997 [Thread-124: 123145319645184]/Users/chengyinliu/anaconda3/lib/python3.7/site-packages/django/core/servers/basehttp.py:log_message:124 INFO - "GET /api/v1.0/service/image/list HTTP/1.1" 200 143
2019-10-08 17:14:01,006 [Thread-125: 123145319645184]/Users/chengyinliu/anaconda3/lib/python3.7/site-packages/django/core/servers/basehttp.py:log_message:124 INFO - "GET /api/v1.0/service/test HTTP/1.1" 200 11
2019-10-08 17:14:01,012 [Thread-126: 123145319645184]/Users/chengyinliu/anaconda3/lib/python3.7/site-packages/django/core/servers/basehttp.py:log_message:124 INFO - "GET /api/v1.0/service/image/list HTTP/1.1" 200 143
2019-10-08 17:14:02,019 [Thread-127: 123145319645184]/Users/chengyinliu/anaconda3/lib/python3.7/site-packages/django/core/servers/basehttp.py:log_message:124 INFO - "GET /api/v1.0/service/test HTTP/1.1" 200 11
2019-10-08 17:14:02,023 [Thread-128: 123145319645184]/Users/chengyinliu/anaconda3/lib/python3.7/site-packages/django/core/servers/basehttp.py:log_message:124 INFO - "GET /api/v1.0/service/image/list HTTP/1.1" 200 143
2019-10-08 17:14:03,033 [Thread-129: 123145319645184]/Users/chengyinliu/anaconda3/lib/python3.7/site-packages/django/core/servers/basehttp.py:log_message:124 INFO - "GET /api/v1.0/service/test HTTP/1.1" 200 11
2019-10-08 17:14:03,038 [Thread-130: 123145319645184]/Users/chengyinliu/anaconda3/lib/python3.7/site-packages/django/core/servers/basehttp.py:log_message:124 INFO - "GET /api/v1.0/service/image/list HTTP/1.1" 200 143
2019-10-08 17:14:04,046 [Thread-131: 123145319645184]/Users/chengyinliu/anaconda3/lib/python3.7/site-packages/django/core/servers/basehttp.py:log_message:124 INFO - "GET /api/v1.0/service/test HTTP/1.1" 200 11
2019-10-08 17:14:04,052 [Thread-132: 123145319645184]/Users/chengyinliu/anaconda3/lib/python3.7/site-packages/django/core/servers/basehttp.py:log_message:124 INFO - "GET /api/v1.0/service/image/list HTTP/1.1" 200 143
2019-10-08 17:14:05,064 [Thread-133: 123145319645184]/Users/chengyinliu/anaconda3/lib/python3.7/site-packages/django/core/servers/basehttp.py:log_message:124 INFO - "GET /api/v1.0/service/test HTTP/1.1" 200 11
2019-10-08 17:14:05,070 [Thread-134: 123145319645184]/Users/chengyinliu/anaconda3/lib/python3.7/site-packages/django/core/servers/basehttp.py:log_message:124 INFO - "GET /api/v1.0/service/image/list HTTP/1.1" 200 143
2019-10-08 17:14:06,079 [Thread-135: 123145319645184]/Users/chengyinliu/anaconda3/lib/python3.7/site-packages/django/core/servers/basehttp.py:log_message:124 INFO - "GET /api/v1.0/service/test HTTP/1.1" 200 11
2019-10-08 17:14:06,084 [Thread-136: 123145319645184]/Users/chengyinliu/anaconda3/lib/python3.7/site-packages/django/core/servers/basehttp.py:log_message:124 INFO - "GET /api/v1.0/service/image/list HTTP/1.1" 200 143
2019-10-08 17:14:07,097 [Thread-137: 123145319645184]/Users/chengyinliu/anaconda3/lib/python3.7/site-packages/django/core/servers/basehttp.py:log_message:124 INFO - "GET /api/v1.0/service/test HTTP/1.1" 200 11
2019-10-08 17:14:07,102 [Thread-138: 123145319645184]/Users/chengyinliu/anaconda3/lib/python3.7/site-packages/django/core/servers/basehttp.py:log_message:124 INFO - "GET /api/v1.0/service/image/list HTTP/1.1" 200 143
2019-10-08 17:14:08,112 [Thread-139: 123145319645184]/Users/chengyinliu/anaconda3/lib/python3.7/site-packages/django/core/servers/basehttp.py:log_message:124 INFO - "GET /api/v1.0/service/test HTTP/1.1" 200 11
2019-10-08 17:14:08,117 [Thread-140: 123145319645184]/Users/chengyinliu/anaconda3/lib/python3.7/site-packages/django/core/servers/basehttp.py:log_message:124 INFO - "GET /api/v1.0/service/image/list HTTP/1.1" 200 143
2019-10-08 17:14:09,127 [Thread-141: 123145319645184]/Users/chengyinliu/anaconda3/lib/python3.7/site-packages/django/core/servers/basehttp.py:log_message:124 INFO - "GET /api/v1.0/service/test HTTP/1.1" 200 11
2019-10-08 17:14:09,131 [Thread-142: 123145319645184]/Users/chengyinliu/anaconda3/lib/python3.7/site-packages/django/core/servers/basehttp.py:log_message:124 INFO - "GET /api/v1.0/service/image/list HTTP/1.1" 200 143
2019-10-08 17:14:10,143 [Thread-143: 123145319645184]/Users/chengyinliu/anaconda3/lib/python3.7/site-packages/django/core/servers/basehttp.py:log_message:124 INFO - "GET /api/v1.0/service/test HTTP/1.1" 200 11
2019-10-08 17:14:10,150 [Thread-144: 123145319645184]/Users/chengyinliu/anaconda3/lib/python3.7/site-packages/django/core/servers/basehttp.py:log_message:124 INFO - "GET /api/v1.0/service/image/list HTTP/1.1" 200 143
2019-10-08 17:14:11,163 [Thread-145: 123145319645184]/Users/chengyinliu/anaconda3/lib/python3.7/site-packages/django/core/servers/basehttp.py:log_message:124 INFO - "GET /api/v1.0/service/test HTTP/1.1" 200 11
2019-10-08 17:14:11,169 [Thread-146: 123145319645184]/Users/chengyinliu/anaconda3/lib/python3.7/site-packages/django/core/servers/basehttp.py:log_message:124 INFO - "GET /api/v1.0/service/image/list HTTP/1.1" 200 143
2019-10-08 17:14:12,180 [Thread-147: 123145319645184]/Users/chengyinliu/anaconda3/lib/python3.7/site-packages/django/core/servers/basehttp.py:log_message:124 INFO - "GET /api/v1.0/service/test HTTP/1.1" 200 11
2019-10-08 17:14:12,186 [Thread-148: 123145319645184]/Users/chengyinliu/anaconda3/lib/python3.7/site-packages/django/core/servers/basehttp.py:log_message:124 INFO - "GET /api/v1.0/service/image/list HTTP/1.1" 200 143
2019-10-08 17:14:13,194 [Thread-149: 123145319645184]/Users/chengyinliu/anaconda3/lib/python3.7/site-packages/django/core/servers/basehttp.py:log_message:124 INFO - "GET /api/v1.0/service/test HTTP/1.1" 200 11
2019-10-08 17:14:13,201 [Thread-150: 123145319645184]/Users/chengyinliu/anaconda3/lib/python3.7/site-packages/django/core/servers/basehttp.py:log_message:124 INFO - "GET /api/v1.0/service/image/list HTTP/1.1" 200 143
2019-10-08 17:14:14,214 [Thread-151: 123145319645184]/Users/chengyinliu/anaconda3/lib/python3.7/site-packages/django/core/servers/basehttp.py:log_message:124 INFO - "GET /api/v1.0/service/test HTTP/1.1" 200 11
2019-10-08 17:14:14,219 [Thread-152: 123145319645184]/Users/chengyinliu/anaconda3/lib/python3.7/site-packages/django/core/servers/basehttp.py:log_message:124 INFO - "GET /api/v1.0/service/image/list HTTP/1.1" 200 143
2019-10-08 17:14:15,231 [Thread-153: 123145319645184]/Users/chengyinliu/anaconda3/lib/python3.7/site-packages/django/core/servers/basehttp.py:log_message:124 INFO - "GET /api/v1.0/service/test HTTP/1.1" 200 11
2019-10-08 17:14:15,236 [Thread-154: 123145319645184]/Users/chengyinliu/anaconda3/lib/python3.7/site-packages/django/core/servers/basehttp.py:log_message:124 INFO - "GET /api/v1.0/service/image/list HTTP/1.1" 200 143
2019-10-08 17:14:16,248 [Thread-155: 123145319645184]/Users/chengyinliu/anaconda3/lib/python3.7/site-packages/django/core/servers/basehttp.py:log_message:124 INFO - "GET /api/v1.0/service/test HTTP/1.1" 200 11
2019-10-08 17:14:16,253 [Thread-156: 123145319645184]/Users/chengyinliu/anaconda3/lib/python3.7/site-packages/django/core/servers/basehttp.py:log_message:124 INFO - "GET /api/v1.0/service/image/list HTTP/1.1" 200 143
2019-10-08 17:14:17,262 [Thread-157: 123145319645184]/Users/chengyinliu/anaconda3/lib/python3.7/site-packages/django/core/servers/basehttp.py:log_message:124 INFO - "GET /api/v1.0/service/test HTTP/1.1" 200 11
2019-10-08 17:14:17,268 [Thread-158: 123145319645184]/Users/chengyinliu/anaconda3/lib/python3.7/site-packages/django/core/servers/basehttp.py:log_message:124 INFO - "GET /api/v1.0/service/image/list HTTP/1.1" 200 143
2019-10-08 17:14:18,278 [Thread-159: 123145319645184]/Users/chengyinliu/anaconda3/lib/python3.7/site-packages/django/core/servers/basehttp.py:log_message:124 INFO - "GET /api/v1.0/service/test HTTP/1.1" 200 11
2019-10-08 17:14:18,282 [Thread-160: 123145319645184]/Users/chengyinliu/anaconda3/lib/python3.7/site-packages/django/core/servers/basehttp.py:log_message:124 INFO - "GET /api/v1.0/service/image/list HTTP/1.1" 200 143
2019-10-08 17:14:19,294 [Thread-161: 123145319645184]/Users/chengyinliu/anaconda3/lib/python3.7/site-packages/django/core/servers/basehttp.py:log_message:124 INFO - "GET /api/v1.0/service/test HTTP/1.1" 200 11
2019-10-08 17:14:19,300 [Thread-162: 123145319645184]/Users/chengyinliu/anaconda3/lib/python3.7/site-packages/django/core/servers/basehttp.py:log_message:124 INFO - "GET /api/v1.0/service/image/list HTTP/1.1" 200 143
2019-10-08 17:14:20,312 [Thread-163: 123145319645184]/Users/chengyinliu/anaconda3/lib/python3.7/site-packages/django/core/servers/basehttp.py:log_message:124 INFO - "GET /api/v1.0/service/test HTTP/1.1" 200 11
2019-10-08 17:14:20,318 [Thread-164: 123145319645184]/Users/chengyinliu/anaconda3/lib/python3.7/site-packages/django/core/servers/basehttp.py:log_message:124 INFO - "GET /api/v1.0/service/image/list HTTP/1.1" 200 143
2019-10-08 17:14:21,328 [Thread-165: 123145319645184]/Users/chengyinliu/anaconda3/lib/python3.7/site-packages/django/core/servers/basehttp.py:log_message:124 INFO - "GET /api/v1.0/service/test HTTP/1.1" 200 11
2019-10-08 17:14:21,332 [Thread-166: 123145319645184]/Users/chengyinliu/anaconda3/lib/python3.7/site-packages/django/core/servers/basehttp.py:log_message:124 INFO - "GET /api/v1.0/service/image/list HTTP/1.1" 200 143
2019-10-08 17:14:22,341 [Thread-167: 123145319645184]/Users/chengyinliu/anaconda3/lib/python3.7/site-packages/django/core/servers/basehttp.py:log_message:124 INFO - "GET /api/v1.0/service/test HTTP/1.1" 200 11
2019-10-08 17:14:22,346 [Thread-168: 123145319645184]/Users/chengyinliu/anaconda3/lib/python3.7/site-packages/django/core/servers/basehttp.py:log_message:124 INFO - "GET /api/v1.0/service/image/list HTTP/1.1" 200 143
2019-10-08 17:14:23,357 [Thread-169: 123145319645184]/Users/chengyinliu/anaconda3/lib/python3.7/site-packages/django/core/servers/basehttp.py:log_message:124 INFO - "GET /api/v1.0/service/test HTTP/1.1" 200 11
2019-10-08 17:14:23,362 [Thread-170: 123145319645184]/Users/chengyinliu/anaconda3/lib/python3.7/site-packages/django/core/servers/basehttp.py:log_message:124 INFO - "GET /api/v1.0/service/image/list HTTP/1.1" 200 143
2019-10-08 17:14:24,367 [Thread-171: 123145319645184]/Users/chengyinliu/anaconda3/lib/python3.7/site-packages/django/core/servers/basehttp.py:log_message:124 INFO - "GET /api/v1.0/service/test HTTP/1.1" 200 11
2019-10-08 17:14:24,371 [Thread-172: 123145319645184]/Users/chengyinliu/anaconda3/lib/python3.7/site-packages/django/core/servers/basehttp.py:log_message:124 INFO - "GET /api/v1.0/service/image/list HTTP/1.1" 200 143
2019-10-08 17:14:25,378 [Thread-173: 123145319645184]/Users/chengyinliu/anaconda3/lib/python3.7/site-packages/django/core/servers/basehttp.py:log_message:124 INFO - "GET /api/v1.0/service/test HTTP/1.1" 200 11
2019-10-08 17:14:25,382 [Thread-174: 123145319645184]/Users/chengyinliu/anaconda3/lib/python3.7/site-packages/django/core/servers/basehttp.py:log_message:124 INFO - "GET /api/v1.0/service/image/list HTTP/1.1" 200 143
2019-10-08 17:14:26,394 [Thread-175: 123145319645184]/Users/chengyinliu/anaconda3/lib/python3.7/site-packages/django/core/servers/basehttp.py:log_message:124 INFO - "GET /api/v1.0/service/test HTTP/1.1" 200 11
2019-10-08 17:14:26,399 [Thread-176: 123145319645184]/Users/chengyinliu/anaconda3/lib/python3.7/site-packages/django/core/servers/basehttp.py:log_message:124 INFO - "GET /api/v1.0/service/image/list HTTP/1.1" 200 143
2019-10-08 17:14:27,409 [Thread-177: 123145319645184]/Users/chengyinliu/anaconda3/lib/python3.7/site-packages/django/core/servers/basehttp.py:log_message:124 INFO - "GET /api/v1.0/service/test HTTP/1.1" 200 11
2019-10-08 17:14:27,414 [Thread-178: 123145319645184]/Users/chengyinliu/anaconda3/lib/python3.7/site-packages/django/core/servers/basehttp.py:log_message:124 INFO - "GET /api/v1.0/service/image/list HTTP/1.1" 200 143
2019-10-10 19:20:01,707 [MainThread: 140405361116928]/root/anaconda3/envs/py36/lib/python3.6/site-packages/django/db/backends/utils.py:execute:111 DEBUG - (0.000) SELECT @@SQL_AUTO_IS_NULL; args=None
2019-10-10 19:20:01,708 [MainThread: 140405361116928]/root/anaconda3/envs/py36/lib/python3.6/site-packages/django/db/backends/utils.py:execute:111 DEBUG - (0.000) SET SESSION TRANSACTION ISOLATION LEVEL READ COMMITTED; args=None
2019-10-10 19:20:01,708 [MainThread: 140405361116928]/root/anaconda3/envs/py36/lib/python3.6/site-packages/django/db/backends/utils.py:execute:111 DEBUG - (0.000) SELECT VERSION(); args=None
2019-10-10 19:20:01,834 [MainThread: 140405361116928]/root/D/WeChatProject/backend/cron/jobs.py:report_by_email:64 INFO - Begin statistics data.
2019-10-10 19:20:01,834 [MainThread: 140405361116928]/root/D/WeChatProject/backend/cron/jobs.py:report_by_email:68 INFO - End statistics data.
